name: Deploy Hello World

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deployment practice
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PracticeApp Build Package
          path: app

      - name: Deploy to Netlify
        run: |
          netlify deploy --prod \
          --dir=app \
          --site ${{secrets.NETLIFY_SITE_ID}} \
          --auth ${{secrets.NETLIFY_API_TOKEN}}