name: Deploy Hello World

on:
  push:
    paths:
      - app2/*

jobs:
  build:
    name: Deployment practice
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Netlify CLI
        run: npm i -g vercel

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PracticeApp Build Package
          path: app2

      - name: Deploy to Netlify
        run: |
          vercel --prod \
          --dir=app2